import React from "react";
import DashboardLayout from "./dashboard/layout";
import { BrainCog, Bot, UserCheck, ListChecks, Lightbulb } from "lucide-react";

const page = () => {
  return (
    <DashboardLayout>
      <div className="max-w-4xl mx-auto py-12 px-6 space-y-10">
        <div className="space-y-4 text-center">
          <h1 className="text-4xl font-bold text-indigo-700">Welcome to AI mock interview platform</h1>
          <p className="text-gray-600 text-lg">
            Your personal AI-powered mock interview assistant. Prepare, practice, and progress with confidence.
          </p>
        </div>

        <div className="space-y-8">
          <div className="flex items-start gap-4">
            <BrainCog className="text-indigo-600 w-8 h-8 mt-1" />
            <div>
              <h2 className="text-xl font-semibold text-gray-800">Smart Mock Interviews</h2>
              <p className="text-gray-600">
                Get personalized mock interview sessions generated by AI based on your experience and role.
              </p>
            </div>
          </div>

          <div className="flex items-start gap-4">
            <Bot className="text-indigo-600 w-8 h-8 mt-1" />
            <div>
              <h2 className="text-xl font-semibold text-gray-800">AI-Powered Feedback</h2>
              <p className="text-gray-600">
                Receive instant ratings and constructive feedback on every answer with suggestions for improvement.
              </p>
            </div>
          </div>

          <div className="flex items-start gap-4">
            <ListChecks className="text-indigo-600 w-8 h-8 mt-1" />
            <div>
              <h2 className="text-xl font-semibold text-gray-800">Detailed Question Analysis</h2>
              <p className="text-gray-600">
                Explore each interview question with correct answers, your responses, and expert feedback.
              </p>
            </div>
          </div>

          <div className="flex items-start gap-4">
            <UserCheck className="text-indigo-600 w-8 h-8 mt-1" />
            <div>
              <h2 className="text-xl font-semibold text-gray-800">Track Your Progress</h2>
              <p className="text-gray-600">
                Review your previous interviews and see your growth over time with a clear rating history.
              </p>
            </div>
          </div>

          <div className="flex items-start gap-4">
            <Lightbulb className="text-indigo-600 w-8 h-8 mt-1" />
            <div>
              <h2 className="text-xl font-semibold text-gray-800">How It Works</h2>
              <p className="text-gray-600">
                Choose your role, experience, and difficulty. Start the interview. Answer questions. Receive instant feedback.
              </p>
            </div>
          </div>
        </div>
      </div>
    </DashboardLayout>
  );
};

export default page;